rob_air_sylius_calendar.admin.booking:
    resource: |
        alias: rob_air_sylius_calendar.booking
        section: admin
        path: /bookings
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: rob_air_sylius_calendar.admin.grid.booking
        vars:
            all:
                header: rob_air_sylius_calendar_plugin.menu.admin.booking.header
                subheader: rob_air_sylius_calendar_plugin.menu.admin.booking.subheader
            index:
                icon: 'calendar alternate outline'
    type: sylius.resource

rob_air_sylius_calendar.admin.calendar:
    resource: |
        alias: rob_air_sylius_calendar.calendar
        section: admin
        path: /calendars
        templates: "@RobAirSyliusCalendarPlugin/SyliusAdminBundleCrud/"
        redirect: update
        grid: rob_air_sylius_calendar.admin.grid.calendar
        vars:
            all:
                header: rob_air_sylius_calendar_plugin.menu.admin.calendar.header
                subheader: rob_air_sylius_calendar_plugin.menu.admin.calendar.subheader
            index:
                icon: 'calendar outline'
    type: sylius.resource
    
rob_air_sylius_calendar.admin.attendant:
    resource: |
        alias: rob_air_sylius_calendar.attendant
        section: admin
        path: /attendants
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: rob_air_sylius_calendar.admin.grid.attendant
        vars:
            all:
                header: rob_air_sylius_calendar_plugin.menu.admin.attendant.header
                subheader: rob_air_sylius_calendar_plugin.menu.admin.attendant.subheader
            index:
                icon: 'users'
    type: sylius.resource

rob_air_sylius_calendar.admin.booking.new:
    path: /bookings/new
    methods: [GET, POST]
    defaults:
        _controller: rob_air_sylius_calendar.controller.booking:createAction
        _sylius:
            section: admin
            permission: true
            factory:
                method: createWithCalendar
            templates:
                form: "@RobAirSyliusCalendarPlugin/Crud/_form.html.twig"
            redirect: rob_air_sylius_calendar.admin.booking
            form:
                options:
                    validation_groups:
                        - sylius
            vars:
                header: rob_air_sylius_calendar_plugin.menu.admin.booking.header
                subheader: rob_air_sylius_calendar_plugin.menu.admin.booking.subheader

rob_air_sylius_calendar.admin.attendant.new:
    path: /attendants/new
    methods: [GET, POST]
    defaults:
        _controller: rob_air_sylius_calendar.controller.attendant:createAction
        _sylius:
            section: admin
            permission: true
            factory:
                method: createWithDefaultCalendar
            templates:
                form: "@RobAirSyliusCalendarPlugin/Crud/_form.html.twig"
            redirect: rob_air_sylius_calendar.admin.attendant
            form:
                options:
                    validation_groups:
                        - sylius
            vars:
                header: rob_air_sylius_calendar_plugin.menu.admin.attendant.header
                subheader: rob_air_sylius_calendar_plugin.menu.admin.attendant.subheader

rob_air_sylius_calendar.admin.booking.product.new:
    path: /products/new/booking
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createAction
        _sylius:
            section: admin
            permission: true
            factory:
#                class: RobAir\SyliusCalendarPlugin\Factory\ProductFactory
                method: createWithVariantAndBooking
            template: "@SyliusAdmin/Crud/create.html.twig"
            redirect: sylius_admin_product_update
            form:
                options:
                    validation_groups:
                        - sylius
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                templates:
                    form: "@SyliusAdmin/Product/_form.html.twig"
                route:
                    name: rob_air_sylius_calendar.admin.booking.product.new
