#rob_air_sylius_calendar_shop_load_events:
#    path: /calendar-load-events
#    defaults:
#        _controller: rob_air_sylius_calendar.controller.calendar_controller::loadAction
#
#rob_air_sylius_calendar_shop_booking_calendar:
#    path: /booking/calendar
#    defaults:
#        _controller: rob_air_sylius_calendar.controller.booking_controller::indexAction

rob_air_sylius_calendar_shop_booking:
    resource: |
        alias: rob_air_sylius_calendar.booking
        section: shop
        path: /bookings
        templates: "@RobAirSyliusCalendarPlugin/booking"
        grid: rob_air_sylius_calendar.shop.grid.booking
        vars:
            all:
                subheader: rob_air_sylius_calendar.ui.booking
            index:
                icon: 'file image outline'
    type: sylius.resource

rob_air_sylius_calendar_shop_calendar:
    resource: |
        alias: rob_air_sylius_calendar.calendar
        section: shop
        path: /calendars
        templates: "@RobAirSyliusCalendarPlugin/calendar"
        grid: rob_air_sylius_calendar.shop.grid.calendar
        vars:
            all:
                subheader: rob_air_sylius_calendar.ui.calendar
            index:
                icon: 'file image outline'
    type: sylius.resource

rob_air_sylius_calendar_shop_booking_load:
    path: /bookings/load
    defaults:
        _controller: rob_air_sylius_calendar.controller.booking::loadAction
        
rob_air_sylius_calendar_shop_booking_update:
    path: /bookings/{id}/edit
    methods: [PUT]
    defaults:
        _controller: rob_air_sylius_calendar.controller.booking::updateAction
        _format: json
        _sylius:
            form:
                type: RobAir\SyliusCalendarPlugin\Form\Type\BookingType
#                options:
#                    data: expr:notFoundOnNull(service('rob_air_sylius_calendar.repository.booking').find(id))
