rob_air_sylius_calendar_shop_load_events:
    path: /calendar-load-events
    defaults:
        _controller: rob_air_sylius_calendar.controller.calendar.calendar_controller::loadAction

rob_air_sylius_calendar_shop_booking_calendar:
    path: /booking/calendar
    defaults:
        _controller: rob_air_sylius_calendar.controller.booking.booking_controller::calendar
