#rob_air_sylius_calendar_shop_load_events:
#    path: /calendar-load-events
#    defaults:
#        _controller: rob_air_sylius_calendar.controller.calendar_controller::loadAction
#
#rob_air_sylius_calendar_shop_booking_calendar:
#    path: /booking/calendar
#    defaults:
#        _controller: rob_air_sylius_calendar.controller.booking_controller::indexAction

rob_air_sylius_calendar_shop_booking:
    resource: |
        alias: rob_air_sylius_calendar.booking
        section: shop
        path: /bookings
        templates: "@RobAirSyliusCalendarPlugin/booking"
        grid: rob_air_sylius_calendar.shop.grid.booking
        vars:
            all:
                subheader: rob_air_sylius_calendar.ui.booking
            index:
                icon: 'file image outline'
    type: sylius.resource

rob_air_sylius_calendar_shop_calendar:
    resource: |
        alias: rob_air_sylius_calendar.calendar
        section: shop
        path: /calendars
        templates: "@RobAirSyliusCalendarPlugin/calendar"
        grid: rob_air_sylius_calendar.shop.grid.calendar
        vars:
            all:
                subheader: rob_air_sylius_calendar.ui.calendar
            index:
                icon: 'file image outline'
    type: sylius.resource

#rob_air_sylius_calendar_shop_booking_show:
#    path: /bookings/show/{id}
#    defaults:
#        _controller: rob_air_sylius_calendar.controller.booking_controller::showAction

rob_air_sylius_calendar_shop_booking_load:
    path: /bookings/load
    defaults:
        _controller: rob_air_sylius_calendar.controller.booking::loadAction
        
