services:
    rob_air_sylius_calendar_form_type_bookingtype:
        class: RobAir\SyliusCalendarPlugin\Form\Type\BookingType
        arguments:
            - "%rob_air_sylius_calendar.model.booking.class%"
            - ['rob_air_sylius_calendar']
        tags:
            - { name: form.type }

    rob_air_sylius_calendar_form_type_attendanttype:
        class: RobAir\SyliusCalendarPlugin\Form\Type\AttendantType
        arguments:
            - "%rob_air_sylius_calendar.model.attendant.class%"
            - [ 'rob_air_sylius_calendar' ]
        tags:
            - { name: form.type }

    #rob_air_sylius_calendar.form.calendar.type:
    #    class: RobAir\SyliusCalendarPlugin\Form\Extension\CalendarTypeExtension
    #    tags:
    #        - { name: form.type_extension, extended_type: Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType }

    rob_air_sylius_calendar.form.type.booking_product:
        class: RobAir\SyliusCalendarPlugin\Form\Type\BookingProductType
        arguments:
            - "%rob_air_sylius_calendar.model.booking.class%"
        tags:
            - { name: form.type }

    rob_air_sylius_calendar.form.extension.type.product:
        class: RobAir\SyliusCalendarPlugin\Form\Extension\ProductTypeExtension
        tags:
            - { name: form.type_extension, extended-type: Sylius\Bundle\ProductBundle\Form\Type\ProductType }
