sylius_grid:
    grids:
        rob_air_sylius_calendar.admin.grid.booking:
            driver:
                name: doctrine/orm
                options:
                    class: RobAir\SyliusCalendarPlugin\Entity\Booking
            fields:
                beginAt:
                    type: datetime
                    label: sylius.ui.starts_at
                endAt:
                    type: datetime
                    label: sylius.ui.ends_at
                calendar:
                    type: twig
                    label: rob_air_sylius_calendar_plugin.ui.calendar
                    options:
                        template: "@RobAirSyliusCalendarPlugin/Grid/Column/_calendar.html.twig"
                title:
                    type: string
                    label: sylius.ui.title
                attendants:
                    type: twig
                    label: rob_air_sylius_calendar_plugin.ui.attendants
                    options:
                        template: "@RobAirSyliusCalendarPlugin/Grid/Column/_collection.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

        rob_air_sylius_calendar.admin.grid.calendar:
            driver:
                name: doctrine/orm
                options:
                    class: RobAir\SyliusCalendarPlugin\Entity\Calendar
            fields:
                title:
                    type: string
                    label: sylius.ui.title
                color:
                    type: twig
                    label: sylius.ui.color
                    options:
                        template: "@RobAirSyliusCalendarPlugin/Grid/Column/_color.html.twig"
                assignedAttendants:
                    type: twig
                    label: rob_air_sylius_calendar_plugin.ui.assigned_attendants
                    options:
                        template: "@RobAirSyliusCalendarPlugin/Grid/Column/_collection.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    show:
                        type: show
                    update:
                        type: update
                    delete:
                        type: delete

        rob_air_sylius_calendar.shop.grid.booking:
            driver:
                name: doctrine/orm
                options:
                    class: RobAir\SyliusCalendarPlugin\Entity\Booking
            fields:
                beginAt:
                    type: datetime
                    label: sylius.ui.starts_at
                endAt:
                    type: datetime
                    label: sylius.ui.ends_at
                title:
                    type: string
                    label: sylius.ui.title
                calendar:
                    type: string
                    label: rob_air_sylius_calendar_plugin.ui.calendar
            actions:
                item:
                    show:
                        type: show

        rob_air_sylius_calendar.shop.grid.calendar:
            driver:
                name: doctrine/orm
                options:
                    class: RobAir\SyliusCalendarPlugin\Entity\Calendar
            fields:
                title:
                    type: string
                    label: sylius.ui.title
            actions:
                item:
                    show:
                        type: show

        rob_air_sylius_calendar.admin.grid.attendant:
            driver:
                name: doctrine/orm
                options:
                    class: RobAir\SyliusCalendarPlugin\Entity\Attendant
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                defaultCalendar:
                    type: string
                    label: rob_air_sylius_calendar_plugin.ui.default_calendar
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
