services:
    rob_air_sylius_calendar.listener.admin.menu_builder:
        class: RobAir\SyliusCalendarPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    rob_air_sylius_calendar.listener.menu.admin_product_form:
        class: RobAir\SyliusCalendarPlugin\Menu\AdminProductFormMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.product.form, method: addItems }
