services:

    rob_air_sylius_calendar.controller.booking.booking_controller:
        class: RobAir\SyliusCalendarPlugin\Controller\Booking\BookingController
        public: true
        autowire: true

    rob_air_sylius_calendar.controller.calendar.calendar_controller:
        class: RobAir\SyliusCalendarPlugin\Controller\Calendar\CalendarController
        arguments:
            - '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
            - '@CalendarBundle\Serializer\Serializer'
        public: true
        autowire: true
        
    rob_air_sylius_calendar.listener.admin.menu_builder:
        class: RobAir\SyliusCalendarPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
