services:

    rob_air_sylius_calendar.controller.booking_controller:
        class: RobAir\SyliusCalendarPlugin\Controller\BookingController
#        public: true
#        autowire: false
#        tags: ['controller.service_arguments']

    rob_air_sylius_calendar.controller.calendar_controller:
        class: RobAir\SyliusCalendarPlugin\Controller\CalendarController
#        public: true
#        autowire: false
#        tags: ['controller.service_arguments']
        
    rob_air_sylius_calendar.listener.admin.menu_builder:
        class: RobAir\SyliusCalendarPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
