<?php

declare(strict_types=1);

namespace RobAir\SyliusCalendarPlugin\Controller;

use Sylius\Bundle\ResourceBundle\Controller\ResourceController;
use Sylius\Bundle\ResourceBundle\Controller\SingleResourceProviderInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class CalendarController extends ResourceController
{

    public function indexAction(Request $request): Response
    {
//        dd($this->metadata);
        return parent::indexAction($request); // TODO: Change the autogenerated stub
    }
}
